# Generated by Django 6.0.1 on 2026-01-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('loan', 'Loan')], max_length=20)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
