# Generated by Django 6.0.1 on 2026-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate as a percentage (e.g., 4.25)', max_digits=5, null=True),
        ),
    ]
