# Generated by Django 6.0.1 on 2026-01-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('charge', 'Charge'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
